version = 0.1
[default.deploy.parameters]
stack_name = "sci-bowl"
resolve_s3 = true
s3_prefix = "sci-bowl"
region = "us-east-1"
profile = "onasmmon"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "S3Bucket=\"eshaan-sci-bowl-paper\" S3Prefix=\"raw-pdf-vault/middle-school/\" DynamoTableName=\"ScienceBowlQuestions\" DynamoTableArn=\"arn:aws:dynamodb:us-east-1:995631985030:table/ScienceBowlQuestions\""
image_repositories = []
