import { NextResponse } from "next/server";
import { InvokeModelCommand } from "@aws-sdk/client-bedrock-runtime";

import { getBedrockClient } from "@/lib/bedrock";

/** The Bedrock model ID to use for explanations. */
const MODEL_ID = "amazon.nova-lite-v1:0";

/** Required fields in the explain request body. */
const REQUIRED_FIELDS = ["question_stem", "answer", "Category", "MatchType"] as const;
type RequiredField = (typeof REQUIRED_FIELDS)[number];

/** Shape of the validated request body. */
interface ExplainRequestBody {
  question_stem: string;
  answer: string;
  Category: string;
  MatchType: string;
}

/**
 * Validates that all required fields are present and non-empty strings.
 * Returns a list of field names that are missing or empty.
 */
function getMissingFields(body: Record<string, unknown>): RequiredField[] {
  return REQUIRED_FIELDS.filter(
    (field) => typeof body[field] !== "string" || (body[field] as string).trim() === ""
  );
}

/**
 * Builds the prompt sent to Bedrock for a given question.
 * Instructs the model to explain the topic in plain language suitable for a student.
 */
function buildPrompt(body: ExplainRequestBody): string {
  return `You are a Science Bowl tutor. A student just saw this ${body.MatchType} question in the ${body.Category} category:

Question: ${body.question_stem}
Answer: ${body.answer}

Please provide a clear, educational explanation of the topic covered by this question. Focus on the underlying concept, why the answer is correct, and any helpful context that would help a student understand and remember this topic. Keep the explanation concise (3-5 sentences) and appropriate for a high school student.`;
}

/**
 * POST /api/explain
 *
 * Accepts { question_stem, answer, Category, MatchType } and returns
 * { explanation: string } generated by an AWS Bedrock model.
 *
 * Returns 400 if any required field is missing or empty.
 * Returns 500 if the Bedrock invocation fails.
 */
export async function POST(request: Request): Promise<NextResponse> {
  let body: Record<string, unknown>;

  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    return NextResponse.json(
      { message: "Invalid JSON in request body" },
      { status: 400 }
    );
  }

  const missingFields = getMissingFields(body);
  if (missingFields.length > 0) {
    return NextResponse.json(
      { message: `Missing or empty required fields: ${missingFields.join(", ")}` },
      { status: 400 }
    );
  }

  const validated = body as unknown as ExplainRequestBody;

  try {
    const client = getBedrockClient();
    const prompt = buildPrompt(validated);

    const payload = {
      messages: [{ role: "user", content: [{ text: prompt }] }],
      inferenceConfig: { maxTokens: 512, temperature: 0.5 },
    };

    const command = new InvokeModelCommand({
      modelId: MODEL_ID,
      contentType: "application/json",
      accept: "application/json",
      body: JSON.stringify(payload),
    });

    const response = await client.send(command);
    const responseBody = JSON.parse(
      new TextDecoder().decode(response.body)
    ) as { output?: { message?: { content?: Array<{ text?: string }> } } };

    const explanation =
      responseBody?.output?.message?.content?.[0]?.text ?? "";

    if (!explanation) {
      return NextResponse.json(
        { message: "Bedrock returned an empty response" },
        { status: 500 }
      );
    }

    return NextResponse.json({ explanation });
  } catch (error) {
    console.error("[POST /api/explain] Bedrock error:", error);
    return NextResponse.json(
      { message: "Failed to generate explanation" },
      { status: 500 }
    );
  }
}
